version: "3.8"

services:
  api:
    container_name: API
    restart: on-failure
    build:
      context: .
      dockerfile: ./Web/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - DatabaseConnectionString=Server=wind-db;Database=Power;User=root;Password=root
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443;
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ob6KdSAOuNB3oe7
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/dev-cert.pfx
    depends_on:
      - wind-db
  wind-db:
    container_name: wind-db
    image: mysql:8.0
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./DataBase:/var/lib/mysql
